project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

#project:
#  type: website
#  title: "我的Python项目博客"  # 博客标题
#  author: "你的名字"
#  description: "基于Quarto的Python项目笔记/教程"
#
#website:
#  navbar:
#    title: "项目博客"
#    left:
#      - href: index.qmd
#        text: 首页
#      - href: posts/
#        text: 文章列表
#  # 允许博客代码块调用项目中的Python文件
#  execute:
#    freeze: auto  # 缓存代码运行结果，加快预览速度
#
#format:
#  html:
#    theme: cosmo  # 博客主题（可选：default、cerulean、journal等）
#    code-fold: true  # 代码块可折叠
#    code-tools: true # 代码块显示复制/运行按钮
#    toc: true  # 侧边目录


